### ISSUE TITLE
Laser

### ISSUE THREAD

**Issue by ManaBingsu** [PMM-Dev/moonshot#144]
- Laser speed
- Laser destroyed time
- Laser effect when collided with player

**Comment by jsuk10** [comment]
* Laser speed 
  - 레이저 속도를 늘리겠습니다.
* Laser destroyed time
 - 가장 마지막 패치에 반영 되었습니다.
* Laser effect when collided with player
 - 이건 기획자랑 논의 해보겠습니다.

**Comment by Kwon770** [comment]
Particle Uploaded
