### ISSUE TITLE
Player Controller 를 통한 조작에 관한 이슈

### ISSUE THREAD

**Issue by Kwon770** [PMM-Dev/moonshot#5]
**확인한 버그**
* 타일의 모서리를 향해 점프한 후 벽점프를 하여 수직으로 점프를 하게 될 경우, 모소리 부분에 점프 모션 그대로 끼는 버그 (영상 첨부)
![ezgif-3-f33b86b24444](https://user-images.githubusercontent.com/49567744/99146120-7b55f180-26b8-11eb-9ea0-725285f878e2.gif)

**개선이 필요해 보이거나 확인이 필요한 점**
* 좌 혹은 우 이동 버튼과 점프 버튼을 동시에 누를경우, 점프력과 속도가 많이 상쇄되는 점
* 점프 인식이 KeyType.Down 이 아니라 KeyType.Stay 이므로 처음 점프를 하기위해 스페이스바를 계속 누르고 있을 경우, 벽에 닿자마자 벽점프를 하는 점 ( 이점은 점프하자마자 빠로 스페이스바를 때지 않으면 의도치않게 벽점프를 하는 상황이 발생)
* 캐릭터의 콜라이더가 벽에 닿기만 하면 벽에 붙은 상태가 아니라도 벽점프가 발동함 (벽점프의 조건이 벽을 잡은 상태가 아닌, 벽에 붙어있는 상태를 확인함)
![ezgif-3-a171579a1884](https://user-images.githubusercontent.com/49567744/99146126-8446c300-26b8-11eb-8ae3-832617f5a3f4.gif)

**Comment by ManaBingsu** [comment]
문제점을 모두 수정하였습니다.
향후 PlayerController의 움직임을 대규모 개편 할 예정으로써 현재 버전을 기반으로 하는 해당 이슈는 close 하겠습니다.
