### ISSUE TITLE
SmoothTargetFollowing 카메라의 z값이 변경됨

### ISSUE THREAD

**Issue by ManaBingsu** [PMM-Dev/moonshot#6]
x, y축만 이동해야하므로 디폴트 값인 -10으로 카메라의 z값이 고정되어야 함.

**Comment by Kwon770** [comment]
카메라가 캐릭터에 붙어버리는 z값 관련 문제는 offSet 을 이용해서 조절하면 됩니다.

**Comment by Kwon770** [comment]
카메라가 캐릭터에 붙어버리는 z값 관련 문제는 offSet 을 이용해서 조절하면 됩니다.
